### ISSUE TITLE
load more articles as user scrolls down

### ISSUE THREAD

**Issue by bluekite2000** [mwaterfall/MWFeedParser#16]
this function is available in google reader but not in MWFeedParser. Currently its limited to 10
Is there a way to do it?

**Comment by mwaterfall** [comment]
MWFeedParser does not limit the number of feed items, it displays all items that are contained in the RSS/Atom XML document.

Google Reader will be constantly pulling in and storing web feed items into a database, so that then they disappear from the current feed they're still accessible.

You could manually replicate this procedure using MWFeedParser if you require.

**Comment by bluekite2000** [comment]
Could you point me to some tutorial so that MWFeedParser will be able to retrieve articles from last week or  last month? Currently it only retrieves whatever is in the xml doc (which has 10 items)

**Comment by mwaterfall** [comment]
You'll have to write some code yourself to archive the feed items (they conform to NSCoding) so you can display them at a later date alongside newer items. Unfortunately I cannot help you with this as it's outside the bounds what MWFeedParser does; however it should be fairly straightforward. Best of luck!
