### ISSUE TITLE
Some feeds not parsed correctly

### ISSUE THREAD

**Issue by sylverb** [mwaterfall/MWFeedParser#38]
I've found that some feeds are not parsed correctly !
This one for example : http://extratorrent.com/rss.xml?type=popular
After investigation, it seems to fail because of the category tag sometimes contains the "& nbsp;" string ("<category>Movie& nbsp;/& nbsp;Action</category>").

**Comment by mwaterfall** [comment]
I've just tested the feed and it appears to be failing due to the XML being invalid. I'd recommend getting in touch with the feed provider and informing them of this problem.

I've updated the demo app to allow it to show items that successfully parsed even if the parsing fails later on in the document. I'll commit and push these changes soon.

**Comment by sylverb** [comment]
You're right, having some html elements in these zones is not compliant to the XML standard !
Thanks

**Comment by sylverb** [comment]
For other people having this issue, check my fork here : https://github.com/sylverb/MWFeedParser , I'm using GDataXMLNode (and libxml2) to parse feeds instead of NSXMLParser. It is allowing to parse almost any feed !
