### ISSUE TITLE
Error with CDATA

### ISSUE THREAD

**Issue by ghost** [mwaterfall/MWFeedParser#41]
Hello,

I've got a feed containing CDATA in the content:encoded
I've got an error each time the parser goes through those CDATA. Here's the URL of the feed : http://www.saintgermainenlaye.fr/no_cache/?type=101

Thanks!

**Comment by acidz** [comment]
The parser looks for &lt;content:encoded&gt; instead of &lt;content&gt;. My suggested solution is to:

1) Change your feed to use &lt;content:encoded&gt; if you don't wish to change MWFeedParser.m, OR
2) Edit MWFeedParser.m and change "/rss/channel/item/content:encoded" to "/rss/channel/item/content".
